# Variables
@baseurl = http://localhost:3333

### 

# Post check language
# @name @check
POST {{baseurl}}/check/typescript
Accept: application/json
Content-Type: application/json

{
    "snippet": "2 + 2"
}

###
